# Generated by Django 2.2.2 on 2019-06-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmEduction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name': '客户表', 'verbose_name_plural': '客户表'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': '报名表', 'verbose_name_plural': '报名表'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '菜单', 'verbose_name_plural': '菜单'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '缴费记录', 'verbose_name_plural': '缴费记录'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': '角色表', 'verbose_name_plural': '角色表'},
        ),
        migrations.AlterModelOptions(
            name='studyrecord',
            options={'verbose_name': '学习记录表', 'verbose_name_plural': '学习记录表'},
        ),
        migrations.AlterModelOptions(
            name='userprofiles',
            options={'verbose_name': '账户表', 'verbose_name_plural': '账户表'},
        ),
        migrations.AlterUniqueTogether(
            name='studyrecord',
            unique_together={('student', 'coursr_record')},
        ),
    ]
