# Generated by Django 2.2.2 on 2019-06-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmEduction', '0002_auto_20190605_0240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': '校区', 'verbose_name_plural': '校区'},
        ),
        migrations.AlterModelOptions(
            name='classtable',
            options={'verbose_name': '班级表', 'verbose_name_plural': '班级表'},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': '课程表', 'verbose_name_plural': '课程表'},
        ),
        migrations.AlterModelOptions(
            name='coursesrecord',
            options={'verbose_name': '上课记录表', 'verbose_name_plural': '上课记录表'},
        ),
        migrations.AlterModelOptions(
            name='customersfollowup',
            options={'verbose_name': '客户跟进表', 'verbose_name_plural': '客户跟进表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AddField(
            model_name='roles',
            name='memus',
            field=models.ManyToManyField(blank=True, to='crmEduction.Menu'),
        ),
        migrations.AlterField(
            model_name='coursesrecord',
            name='day_num',
            field=models.PositiveSmallIntegerField(verbose_name='第几天'),
        ),
    ]
